---
engines:
  duplication:
    enabled: true
    config:
      languages:
      - python
  fixme:
    enabled: true
  radon:
    enabled: true
  pep8:
    enabled: true
    checks:
      E501:
        enabled: false
      E203:
        enbled: false
      W503:
        enabed: false
ratings:
  paths:
  - "**.py"

exclude_paths:
# - tests/
- data/
- precision/
- venv/
- plots/

# Change check defaults
# https://docs.codeclimate.com/docs/advanced-configuration#section-default-check-configurations
version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 6
  complex-logic:
    config:
      threshold: 4
  file-lines:
    config:
      threshold: 400
  method-complexity:
    config:
      threshold: 10
  method-count:
    config:
      threshold: 20
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 4
  return-statements:
    config:
      threshold: 4
 # similar-code:
 #   config:
 #     threshold: # language-specific defaults. an override will affect all languages.
 # identical-code:
 #   config:
 #     threshold: # language-specific defaults. an override will affect all languages.
