language: python
python:
    - 3.6
    - 3.7

build:
  cache: true

  cache_dir_list:
      - $HOME/.cache/pip
      - $HOME/tests/data
      - $HOME/data

  ci:
    # - pip install --upgrade pip
    # Install eniric requirements
    - travis_retry pip install -r requirements_dev.txt
    - travis_retry pip install -r requirements.txt

    # Now install eniric
    - pip install -e .[dev,test,docs,ci]

    # Setup config and make test data
    - export MPLBACKEND="AGG"  # Non-interactive
    # - mv tests/config.yaml config.yaml

    # Download the Data for eniric and testing
    - download_eniric_data.sh  # Some files from Dropbox

    # Prepare atmosphere models
    - make atmos

    # Create folders for test and code coverage
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage

    # Run test and code coverage and output results to the right folder
    - pytest --junitxml=shippable/testresults/nosetests.xml
    - pytest --cov=. --cov-report=xml:shippable/codecoverage/coverage.xml --durations=10

  on_success:
    - coverage xml -i
