language: python
python:
    - 3.6
    - 3.7

build:
  cache: true

  cache_dir_list:
      - $HOME/.cache/pip

  ci:
    # Install eniric requirements
    - travis_retry pip install -r requirements.txt
    - travis_retry pip install -r requirements_dev.txt

    # Install Starfish
    - wget -O starfishrequirements.txt https://raw.githubusercontent.com/iancze/Starfish/master/requirements.txt
    - pip install -r starfishrequirements.txt
    - pip install https://github.com/iancze/Starfish/archive/master.zip#egg=Starfish

    # Now install eniric
    - python setup.py install

    # Setup config and make test data
    - export MPLBACKEND="AGG"  # Non-interactive
    - mv tests/config.yaml config.yaml
    # Generate data
    - make_test_data.py
    # Prepare atmosphere models
    - make atmos

    # Create folders for test and code coverage
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage

    # Run test and code coverage and output results to the right folder
    - pytest --junitxml=shippable/testresults/nosetests.xml
    - pytest --cov=. --cov-report=xml:shippable/codecoverage/coverage.xml --durations=10

  on_success:
    - coverage xml -i
