language: python
python:
    - 3.6
    - 3.7

before_install:
  # http://conda.pydata.org/docs/travis.html
  - travis_retry sudo apt-get update
  - travis_retry wget https://repo.continuum.io/miniconda/Miniconda3-latest-Linux-x86_64.sh -O miniconda.sh;
  - bash miniconda.sh -b -p $HOME/miniconda
  - export PATH="$HOME/miniconda/bin:$PATH"
  - hash -r
  - conda config --set always_yes yes --set changeps1 no
  - conda config --add channels conda-forge
  - conda update -q conda
  - conda info -a

cache:
  directories:
    - $HOME/.cache/pip

install:
  - conda create -q -n test-environment python=$TRAVIS_PYTHON_VERSION
  - source activate test-environment

  # Install heavy science packages
  - travis_retry conda install --yes astropy cython emcee h5py matplotlib scikit-learn scipy

  # Install eniric requirements
  - travis_retry pip install -r requirements.txt
  - travis_retry pip install -r requirements_dev.txt

  # Install Starfish
  - cd $HOME
  - travis_retry git clone https://github.com/iancze/Starfish.git
  - cd Starfish
  - travis_retry pip install -r requirements.txt
  - python setup.py build_ext --inplace
  - python setup.py develop

  # Now install eniric
  - cd $SHIPPABLE_BUILD_DIR
  - python setup.py install

  # Setup config and make data
  # This is not the best place to put this but pre_ci didn't work.
  - mv tests/config.yaml config.yaml
  # Generate data
  - make_test_data.py
  # Prepare atmosphere models
  - make atmos

build:
  # pre_ci:
  #   - mv tests/config.yaml config.yaml
  #   # Generate data
  #   - python eniric_scripts/make_test_data.py

  ci:
    # Create folders for test and code coverage
    - mkdir -p shippable/testresults
    - mkdir -p shippable/codecoverage

    # Run test and code coverage and output results to the right folder
    - pytest --junitxml=shippable/testresults/nosetests.xml
    - pytest --cov=. --cov-report=xml:shippable/codecoverage/coverage.xml --durations=10
    # - pytest --cov=. --cov-report term-missing

after_success:
  - coverage xml -i
