# YAML configuration script

name: eniric_default

# The parameters defining the spectral libraries live here.
paths:
  phoenix_raw: ["..","..","data", "test_data","phoenix-raw"]
  btsettl_raw: ["..","..","data", "test_data", "BT-Settl"]
  atmmodel: ["..","..","data", "atmmodel"]
  precision: ["precision"]
  test_data: ["..","..","data","test_data"]

cache:
  # location: None  # Disables cache
  location: [".joblib"]

atmmodel:
  # Base name of telluric model
  base: "Average_TAPAS_2014"

# Wavelength bands.
bands:
  all: ["VIS", "K", "H", "J", "Y", "Z", "CONT", "NIR", "GAP", "CARMENES_NIR", "CARMENES_VIS", "TEST"]

# Add your custom band limits here
custom_bands:
  CARMENES_NIR: [0.96, 1.71]
  CARMENES_VIS: [0.52, 0.96]
  TEST: [2.1,2.2]


## Starfish Keywords
name: ""
outdir: ""
plotdir: ""
grid:
  raw_path: ""
  hdf5_path: ""
  key_name: ""
  parname: []
  parrange: []
  wl_range: []
  buffer: 0
data:
  grid_name: ""
  instruments: []
