
# coding: utf-8

# # Table of Contents
# * [Plot showing the derivation of precision.](#Plot-showing-the-derivation-of-precision.)
# 

# #  Plot showing the derivation of precision.

# [Connes 1985](#cite-Connes1985)   https://doi.org/10.1007/BF00653671

# In[1]:


import numpy as np
import matplotlib.pyplot as plt


# In[2]:


x = np.arange(0,  1.6, 0.01)

sigma = 0.2
mean = .7
mean2 = mean+ 0.08
ax = plt.subplot(111)
g1 = lambda x: 1 - 0.5/np.sqrt(2*np.pi*sigma**2) * np.exp(-(x-mean)**2 / 2 / sigma**2)
g2 = lambda x: 1 - 0.5/np.sqrt(2*np.pi*sigma**2) * np.exp(-(x-mean2)**2 / 2 / sigma**2) 
#y2 = np.cos(x + np.pi/12)

ax.plot(x, g1(x), ".", label="A$_0$")
ax.plot(x, g2(x), ".", label="A")

#plt.axvline(0.5, -.5, g1(0.5))
#plt.axvline(x=0, ymin=0, ymax=1, hold=None, **kwargs)
get_ipython().run_line_magic('pinfo', 'plt.axvline')
x1 = 0.48
x2 = 0.55
y1 = g1(x1)
y2 = g2(x1)
y3 = g2(x2)

ax.axvline(x=x1, ymin=0, ymax=y2, color="blue")
ax.axvline(x=x1, ymin=0, ymax=y1, color="red")
ax.axvline(x=x2, ymin=0, ymax=y3, color="orange")
ax.axhline(y=y2, xmin=0, xmax=x1, color="green")
ax.axhline(y=y3, xmin=0, xmax=x2, color="black")

plt.xlabel("$\lambda$")
plt.annotate(s="$\delta \lambda$", xy=(0.32, 0.2), xycoords="axes fraction")
plt.annotate(s="$A$", xy=(0.01, 0.7), xycoords="axes fraction")
plt.annotate(s="$A_0$", xy=(0.01, 0.5), xycoords="axes fraction")

plt.legend()
plt.show()


# In[3]:


plt.plot()
plt.axvline(0.5, 0, 0.5)
plt.axhline(0.5, 0, 0.5, color="red")


# In[ ]:


<!--bibtex

@article{Connes1985,
  title = {Absolute Astronomical Accelerometry},
  volume = {110},
  issn = {1572-946X},
  doi = {10/dk66bp},
  abstract = {Two distinct but fully compatible novel concepts are proposed here for solar/stellar velocity measurements. The first is that of absolute accelerometry proper. This involves two simultaneously, operating servo-control loops First, a variable path-difference Fabry-Perot interferometer is adjusted so that its bandpasses track the fluctuations of either a single spectral line (in the solar case, leading to the solar accelerometer), or of all lines simultaneously (stellar accelerometer). The second loop involves a tunable laser tracking one of the FP bandpasses. The net overall result is that a laser line tracks the stellar/solar ones: the problem of measuring Doppler-shift changes has been transferred from the incoherent to the coherent optics domain. One then measures the beat frequency generated by mixing the tunable laser beam with that of stabilized laser. Only velocity changes are accessible; the devices are true accelerometers, but absolute ones. All instrumental or spectral characteristics drop out; no calibration of any kind is required; hence, one may hope for an unusually low level of systematic errors.},
  number = {2},
  journal = {Astrophysics and Space Science},
  author = {Connes, Pierre},
  month = mar,
  year = {1985},
  pages = {211-255},
  day = {01}
}
-->


# # References
# 
# 
